# bridge_params.yaml

- ros_topic_name: "/robot/imu/data"
  gz_topic_name: "/robot/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/robotnik_base_controller/cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"
  
- ros_topic_name: "/robot/robotnik_base_controller/cmd_vel"
  gz_topic_name: "cmd_vel_rear"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"

- ros_topic_name: "/robot/front_laser/scan"
  gz_topic_name: "/robot/front_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/robot/rear_laser/scan"
  gz_topic_name: "/robot/rear_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/robot/robotnik_base_controller/odometry"
  gz_topic_name: "/model/robot/rbrobout/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/robot/front_rgbd_camera/color/image_raw"
  gz_topic_name: "/robot/front_camera_color/color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
 
- ros_topic_name: "/robot/front_rgbd_camera/color/camera_info"
  gz_topic_name: "/robot/front_camera_color/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/robot/rear_rgbd_camera/color/image_raw"
  gz_topic_name: "/robot/rear_camera_color/color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/robot/rear_rgbd_camera/color/camera_info"
  gz_topic_name: "/robot/rear_camera_color/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
  
- ros_topic_name: "/tf"
  gz_topic_name: "/model/robot/rbrobout/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/robot/joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"
