<?xml version="1.0"?>
<robot name="sensor_gps_with_mast" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="mast_height" value="0.5" />
  <xacro:property name="mast_radius" value="0.010" />

	<xacro:macro name="sensor_gps_with_mast"
			params="frame_prefix
					parent
					*origin
					simulation:=false
					node_name:=gps_with_mast
					node_namespace:=${None}
					topic_prefix:=~/
					update_rate:=5.0">

	  <!-- MAST OF THE ANTENNA GPS -->
	  <joint name="${frame_prefix}joint" type="fixed">
	    <xacro:insert_block name="origin"/>
	    <parent link="${parent}"/>
	    <child link="${frame_prefix}mast_base_link"/>
	  </joint>

	  <link name="${frame_prefix}mast_base_link">
		<inertial>
			<origin xyz="0.0 0 0.0" rpy="0 0 0" />
			<mass value="1.0" />
			<xacro:solid_cuboid_inertia m="1.0" w="${mast_radius}" h="${mast_radius}" d="${mast_height}" />
		</inertial>
	    <visual>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <material name="mast_color">
            <color rgba="0.1 0.1 0.1 1"/>
          </material>
	      <geometry>
	        <cylinder length="${mast_height}" radius="${mast_radius}" />
	      </geometry>
	    </visual>
	    <collision>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <geometry>
	        <cylinder length="${mast_height}" radius="${mast_radius}" />
	      </geometry>
	    </collision>
	  </link>

	  <joint name="${frame_prefix}mast_joint" type="fixed">
	    <parent link="${frame_prefix}mast_base_link"/>
	    <child link="${frame_prefix}base_link"/>
	    <origin xyz="0 0 ${mast_height/2.0}" rpy="0 0 0" />
	  </joint>

	  <gazebo reference="${frame_prefix}mast_base_link">
	    <material>Gazebo/Black</material>
	    <gravity>true</gravity>
	  </gazebo>

      <!-- ANTENNA GPS -->
	  <link name="${frame_prefix}base_link">
	    <inertial>
			<origin xyz="0.0 0 0.015" rpy="0 0 0" />
			<mass value="0.2" />
			<xacro:solid_cuboid_inertia m="0.2" w="0.081" h="0.081" d="0.03" />
      	</inertial>
	    <visual>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <material name="gps_color">
           <color rgba="1 1 1 1"/>
        </material>
	      <geometry>
	        <mesh filename="package://robotnik_sensors/meshes/gps/antenna_3GO16.stl" scale="1.0 1.0 1.0"/>
	      </geometry>
	    </visual>
	    <collision>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <geometry>
	        <mesh filename="package://robotnik_sensors/meshes/gps/antenna_3GO16.stl" scale="1.0 1.0 1.0"/>
	      </geometry>
	    </collision>
	  </link>


	<gazebo reference="${frame_prefix}base_link">
	<material>Gazebo/White</material>
	<gravity>true</gravity>
	</gazebo>

    <xacro:if value="${simulation}">
		<gazebo reference="${frame_prefix}base_link">
		<sensor type="gps" name="${frame_prefix}sensor">
			<always_on>true</always_on>
			<update_rate>${update_rate}</update_rate>
			<gps>
			<position_sensing>
				<horizontal>
				<noise type="gaussian">
					<mean>0.0</mean>
					<stddev>0.1</stddev>
				</noise>
				</horizontal>
				<vertical>
				<noise type="gaussian">
					<mean>0.0</mean>
					<stddev>0.1</stddev>
				</noise>
				</vertical>
			</position_sensing>
			<vertical_sensing>
				<horizontal>
				<noise type="gaussian">
					<mean>0.0</mean>
					<stddev>0.1</stddev>
				</noise>
				</horizontal>
				<vertical>
				<noise type="gaussian">
					<mean>0.0</mean>
					<stddev>0.1</stddev>
				</noise>
				</vertical>
			</vertical_sensing>
			</gps>
			<plugin name="${node_name}" filename="libgazebo_ros_gps_sensor.so">
			<ros>
				<namespace>${node_namespace}</namespace>
				<remapping>~/out:=${topic_prefix}fix</remapping>
				<remapping>~/vel:=${topic_prefix}vel</remapping>
			</ros>
			</plugin>
		</sensor>
		</gazebo>
    </xacro:if>

  </xacro:macro>

</robot>
