/**:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  joint_state_broadcaster:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200

  joint_trajectory_controller:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200
      joints:
        - front_sensor_tilt_joint
        - front_sensor_pan_joint

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      allow_partial_joints_goal: false
      open_loop_control: true
